name: Renovate

on:
  push:
    branches: ["main"]

  schedule:
    - cron:  '15 4 * * *'
  
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Renovate
        uses: renovatebot/github-action@v39.2.1
        env:
          RENOVATE_BRANCH_PREFIX: 'github-action-renovate/'
          RENOVATE_AUTODISCOVER: 'true'
          RENOVATE_AUTODISCOVER_NAMESPACES: ${{ github.repository_owner }}
          RENOVATE_AUTODISCOVER_TOPICS: 'managed-by-renovate'
          RENOVATE_ASSIGNEES: ${{ github.repository_owner }}
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
